config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get '/about' => 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates_presence_of :title, length: {minimum: 3, maximum: 50}
  validates :description, presence: true , length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
            length: {minimum: 3, maximum: 25}
             
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: {case_sensitive: false}, 
            length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, 
            length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :set_user, only: %i[ create]
  before_action :require_user, except: %i[index show ]
  before_action :require_same_user, only: %i[edit update destroy ]

  def index
    @articles = Article.paginate(page: params[:page])
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article successfully created'
      redirect_to article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params) 
      flash[:success] = 'Article successfully updated'
      redirect_to article_url(@article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article successfully destroyed'
    redirect_to articles_url
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_user
    @user = User.first#User.find(params[:user_id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :user_id, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You  can only edit or delete your own article'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update]

  def index
    @categories = Category.paginate(page: params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category successfully created'
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page])
  end

  def edit

  end

  def update
    if @category.update(category_params) 
      flash[:success] = 'Category successfully updated'
      redirect_to category_url(@category)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = 'Only admin users can perform that function'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'There was something wrog with your login'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy ]
  before_action :require_admin, only: [:destory]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Bog #{@user.username}"
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was successfully updated'
      redirect_to articles_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = 'User successfully destroyed'
    redirect_to users_url
  end

  
  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = 'You  can only edit your own account'
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = 'Only admin users can perform that function'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatr.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class='row'>
    <div class='col-md-8 offset-md-2'>
      <div class='card' style="margin-bottom: 2rem;">
        <div class="card-body">
          <div class='article-title'>
            <%= link_to article.title.capitalize, article_path(article) %>
          </div>
          <div class='article-body'>
            <%= truncate(article.description, length: 100 ) %>
            <div class='article-meta-details'>
              <small>Created by: <%= article.user.username if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago, 
                last updated: <%= time_ago_in_words(article.updated_at) %></small> 
            </div>
          </div>
          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %></p>
          <% end %>
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <div class='article-actions'>
              <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-primary' %>
              <%= link_to 'Delete', article, class: 'btn btn-sm btn-danger' , turbo_method: :delete, data: {turbo_confirm: "Are you sure?" } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for @article do |f| %>
      <%= render 'shared/errors', obj: @article %>
      
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :title %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :description %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Description of article'  %>
        </div>
      </div> 
      <div class='form-group'>
        <div class='row'>
          <div class='offset-sm-2 col-sm-8'>
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div> 
      <div class='form-group'>
        <div class='col-sm-10'>
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

  
<%= render 'form' %>
<%= link_to "Back to articles", articles_path %>

app/views/articles/index.html.erb
<h1 align='center'>Listing all Articles</h1>


<%= render 'article', obj: @articles %>

<div align='center'>
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h1>

  
<%= render 'form' %>
<%= link_to "Cancel request and return to articles", articles_path %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 offset-xs-2 ">
  <% if @article.user %>
    <ul class='listing'>
      <div class='row center'>
        <div class='col-md-4 offset-md-4'>
          <li>Created by: </li>
          <li>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          </li> 
          <li class='article-title'>
            <%= link_to @article.user.username.capitalize, user_path(@article.user) %>
          </li>
          <li>
            <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class='article-actions'>
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-sm btn-primary' %>
      <%= link_to 'Delete', @article, class: 'btn btn-sm btn-danger' , turbo_method: :delete, data: {turbo_confirm: "Are you sure?" } %>
    <% end %>    
    <%= link_to "View all articles", articles_path, class: 'btn btn-sm btn-success'  %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %><%%> &nbsp;</span>

app/views/categories/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for @category do |f| %>
      <%= render 'shared/errors', obj: @category %>
      
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :name %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name of category' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='col-sm-10'>
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= render 'form' %>
<%= link_to "Back to categories", categories_path %>

app/views/categories/index.html.erb
<h1 align='center'>Listing all Categories</h1>
<div align='center'>
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class='listing'>
      <div class='row'>
        <div class='col-md-4 offset-md-4'>
          <div class='card' style="margin-bottom: 2rem;">
            <div class="card-body">
              <li class='article-title'>
                <%= link_to category.name, category_path(category) %>
              </li>
              <li>
                <small><%= pluralize(category.articles.count, "article") %></small>
              </li>
              <% if logged_in? && current_user.admin? %>
                <li>
                  <%= link_to 'Delete this category', category_path(category), class: 'btn btn-sm btn-danger' , turbo_method: :delete, data: {turbo_confirm: "Are you sure?" } %>
                </li>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>Create a category</h1>
  
<%= render 'form' %>
<%= link_to "Cancel request and return to categories", categories_path %>

app/views/categories/show.html.erb
<h1 align='center'><%=  "Category: " + @category.name %></h1>

<div align='center'>
  <% if logged_in? && current_user.admin? %>
    <span class='badge'><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
  <% end %>
</div>
<%= render 'articles/article', obj: @category_articles %>

<div align='center'>
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class='container'>
  <footer class='footer'>
    <small>
      Copyright &copy 2023: Alpha Blog by Chima
    </small>
    <nav>
      <ul>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class='container row'>
  <div class='col-md-10 col-md-offset-1'>
    <% flash.each do |name, msg| %>
      <div class='badge badge-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="badge">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand" href="/" id="logo">AlphaBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Articles',  articles_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users',  users_path, class:'nav-link' %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Create Article', new_article_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> 
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%= link_to 'All Categories', categories_path, class: "dropdown-item" %>
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category), class: "dropdown-item" %>
          <% end %>
          <% if logged_in? and current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Create New category', new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li> 
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, turbo_method: :delete, class:'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit your profile', edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'View your profile', user_path(current_user), class: "dropdown-item" %>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Signup', signup_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class:'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Try</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <%= render 'layouts/messages' %>
    <div class='container' style='padding-top:50px;'>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<%= link_to 'Home',  root_path %>

app/views/pages/home.html.erb
<div class='center jumbotron'>
    <h1>ALPHA BLOG</h1>
      <%= link_to 'SignUp Now', signup_path, class: 'btn btn-danger btn-lg btn-xlarge' %>
    
    </div>
<%= link_to 'About', about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='col-md-8 col-md-offset-2'>
      <div class='alert alert-danger'>
        <div class='alert-heading'>
          <h2 class='alert-title'>
            <%= pluralize(obj.errors.count, 'error')%> 
            prevented the article from being saved:
          </h2>
          <div class='alert-body'>
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for @user do |f| %>
      <%= render 'shared/errors', obj: @user %>
      
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :username %>
        </div>
        <div class='col-sm-12'>
          <%= f.text_field :username, class: 'form-control', placeholder: 'Enter username' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :email %>
        </div>
        <div class='col-sm-12'>
          <%= f.email_field :email, class: 'form-control', placeholder: 'Enter email'  %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :password %>
        </div>
        <div class='col-sm-12'>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Enter password'  %>
        </div>
      </div>
      <div class='form-group'>
        <div class='col-sm-10'>
          <%= f.submit(@user.new_record? ? 'Signup' : 'Update User', class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align='center'>Edit your account</h1>

  
<%= render 'form' %>
<%= link_to "Cancel request and return to articles", articles_path %>

app/views/users/index.html.erb
<h1 align='center'>All Alpha Bloggers</h1>
<div align='center'>
  <% @users.each do |user| %>
    <ul class='listing'>
      <div class='row'>
        <div class='col-md-4 offset-md-4'>
          <div class='card' style="margin-bottom: 2rem;">
            <div class="card-body">
              <li>
                <%= link_to gravatar_for(user), user_path(user) %>
              </li>
              <li class='article-title'>
                <%= link_to user.username.capitalize, user_path(user) %>
              </li>
              <li>
                <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
              </li>
              <% if logged_in? && current_user.admin? %>
                <li>
                  <%= link_to 'Delete this user', user_path(user), class: 'btn btn-sm btn-danger' , turbo_method: :delete, data: {turbo_confirm: "Are you sure?" } %>
                </li>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </ul>
  <% end %>
</div>

<div align='center'>
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h1 align='center'>Signup for Alpha Blog</h1>

  
<%= render 'form' %>
<%= link_to "Cancel request and return to articles", articles_path %>

app/views/users/show.html.erb
<h1 align='center'>Welcome to <%= @user.username %>'s page</h1>
<div class='row'>
  <div class="col-md-4 offset-md-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align='center'><%= @user.username %>'s articles</h4>

<%= render 'articles/article', obj: @user_articles %>
<div align='center'>
  <%= will_paginate @user_articles %>
</div>
 